### ISSUE TITLE
edge cases

### ISSUE THREAD

**Issue by pekeler** [shama/yo-yoify#23]
The following examples throw a "bel is not a function" error at runtime. They work fine when not using yo-yoify.

``` JavaScript
bel('<div>fun stuff</div>')
bel('')
bel``
```

**Comment by shama** [comment]
`bel` is only intended to be used as a tagged template string that contains a single wrapping element.

**Comment by pekeler** [comment]
So if I'm using bel like

``` JavaScript
const stuff = ['<span>one</span>', ...
bel`<div>${bel(stuff[offset])}</div>`
```

are you saying this pattern may not work with future versions of bel anymore?

I find this pattern useful as a workaround for https://github.com/shama/bel/issues/42. If bel wouldn't escape by default, I could just do

``` JavaScript
const stuff = ['<span>one</span>', ...
bel`<div>${stuff[offset]}</div>`
```

and wouldn't have this issue with yo-yoify either :)

**Comment by shama** [comment]
No I don't support it or see any reason to support calling bel as a function. It's for tagged template literals. `yo-yoify` only replaces tagged template strings. It doesn't replace function calls and why you're getting the error `bel is not a function`.

If you can find a way to better support entities without sacrificing security I'd consider a patch. Otherwise feel free to fork or build your own library that doesn't escape by default. That's the great thing about these libraries, if you don't agree with the maintainer, it's a simple task to switch them out for your own. ;)
