### ISSUE TITLE
TypeError: html is not a function

### ISSUE THREAD

**Issue by davidguttman** [shama/yo-yoify#26]
Get that error at this line: https://github.com/davidguttman/overwatch-voter/blob/yo-yoify/client/views/main.js#L30 (see https://github.com/davidguttman/overwatch-voter/blob/yo-yoify/package.json#L7 for setup)

Issue with `choo` compatibility? 

cc @yoshuawuyts

**Comment by yoshuawuyts** [comment]
odd, yeah that doesn't seem right - you're using choo@3 so this shouldn't
be happening. Hmmmmmmm

**Comment by rollymaduk** [comment]
Hi having the same problem, were you able to resolve it?

**Comment by davidguttman** [comment]
Nope, was hoping @yoshuawuyts would work some magic =)

**Comment by yoshuawuyts** [comment]
hmm, perhaps @shama can help / have you tried digging in yourself? - not
overly familiar with the yo-yoify code tbh

**Comment by shama** [comment]
@davidguttman This is because `es2020` is transpiling the template strings before `yo-yoify` can get to it.

The simple solution is run them at the same level and put `yo-yoify` before `es2020`.

`-g yo-yoify -g es2020` or `-t yo-yoify -t es2020`

If `yo-yoify` isn't ran globally, it won't remove some unneeded deps and you'll get a few more bytes in your bundle. If `es2020` is ran globally you might end up transpiling somethings you may not intend.

I recommend just running both globally.

**Comment by davidguttman** [comment]
That makes perfect sense, thank you!
